services:

    dn-node:
        container_name: dn-node
        image: dn-node
        build:
            context: ./node
            dockerfile: Dockerfile
        ports:
            - "3000:3000"
        volumes:
            - ./node:/usr/src/app
            - /usr/src/app/node_modules
        depends_on:
            dn-db:
                condition: service_healthy
        networks:
            - dn-net

    dn-nginx:
        container_name: dn-nginx
        image: dn-nginx
        build:
            context: ./nginx
            dockerfile: Dockerfile
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        ports:
            - "8080:80"
        depends_on:
            -   dn-node
        networks:
            - dn-net

    dn-db:
        image: mysql:5.7
        command: --innodb-use-native-aio=0
        container_name: dn-db
        tty: true
        volumes:
            - ./mysql:/var/lib/mysql
        environment:
            - MYSQL_DATABASE=dn-db
            - MYSQL_ROOT_PASSWORD=root
        networks:
            - dn-net
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
            interval: 30s
            timeout: 10s
            retries: 5

networks:
    dn-net:
        driver: bridge